export const ErrorCode = {
  CLI_USAGE_ERROR: "CLI_USAGE_ERROR",
  CONFIG_VALIDATION_ERROR: "CONFIG_VALIDATION_ERROR",
  WORKFLOW_PARSE_ERROR: "WORKFLOW_PARSE_ERROR",
  WORKFLOW_VALIDATION_ERROR: "WORKFLOW_VALIDATION_ERROR",
  PROVIDER_UNAVAILABLE: "PROVIDER_UNAVAILABLE",
  PROVIDER_PROCESS_FAILED: "PROVIDER_PROCESS_FAILED",
  PROCESS_TIMEOUT: "PROCESS_TIMEOUT",
  SCHEMA_VALIDATION_FAILED: "SCHEMA_VALIDATION_FAILED",
  SECURITY_POLICY_VIOLATION: "SECURITY_POLICY_VIOLATION",
  USER_CANCELLED: "USER_CANCELLED",
  WORKFLOW_PENDING: "WORKFLOW_PENDING",
  ARTIFACT_WRITE_FAILED: "ARTIFACT_WRITE_FAILED",
  BUDGET_EXCEEDED: "BUDGET_EXCEEDED",
  MODEL_CONFIG_INVALID: "MODEL_CONFIG_INVALID",
  MODEL_NOT_SUPPORTED: "MODEL_NOT_SUPPORTED",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
