export const ErrorCode = {
  CLI_USAGE_ERROR: "CLI_USAGE_ERROR",
  CONFIG_VALIDATION_ERROR: "CONFIG_VALIDATION_ERROR",
  WORKFLOW_PARSE_ERROR: "WORKFLOW_PARSE_ERROR",
  WORKFLOW_VALIDATION_ERROR: "WORKFLOW_VALIDATION_ERROR",
  PROVIDER_UNAVAILABLE: "PROVIDER_UNAVAILABLE",
  PROVIDER_PROCESS_FAILED: "PROVIDER_PROCESS_FAILED",
  PROCESS_TIMEOUT: "PROCESS_TIMEOUT",
  SCHEMA_VALIDATION_FAILED: "SCHEMA_VALIDATION_FAILED",
  SECURITY_POLICY_VIOLATION: "SECURITY_POLICY_VIOLATION",
  USER_CANCELLED: "USER_CANCELLED",
  ARTIFACT_WRITE_FAILED: "ARTIFACT_WRITE_FAILED",
  MODEL_CONFIG_INVALID: "MODEL_CONFIG_INVALID",
  MODEL_NOT_SUPPORTED: "MODEL_NOT_SUPPORTED",
  UNSUPPORTED_CAPABILITY: "UNSUPPORTED_CAPABILITY",
  SHARED_AGENT_NOT_FOUND: "SHARED_AGENT_NOT_FOUND",
  SHARED_AGENT_INVALID_DEFINITION: "SHARED_AGENT_INVALID_DEFINITION",
  SHARED_AGENT_DUPLICATE_ID: "SHARED_AGENT_DUPLICATE_ID",
  SHARED_AGENT_CONTEXT_VALIDATION_FAILED: "SHARED_AGENT_CONTEXT_VALIDATION_FAILED",
  SHARED_AGENT_PROMPT_RENDER_FAILED: "SHARED_AGENT_PROMPT_RENDER_FAILED",
  SHARED_AGENT_UNDECLARED_PROMPT_VARIABLE: "SHARED_AGENT_UNDECLARED_PROMPT_VARIABLE",
  SHARED_AGENT_SECURITY_POLICY_VIOLATION: "SHARED_AGENT_SECURITY_POLICY_VIOLATION",
  SHARED_AGENT_RUNTIME_FAILED: "SHARED_AGENT_RUNTIME_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
