export type OpenFlowErrorCode =
  | "CLI_USAGE_ERROR"
  | "CONFIG_VALIDATION_ERROR"
  | "WORKFLOW_PARSE_ERROR"
  | "WORKFLOW_VALIDATION_ERROR"
  | "PROVIDER_UNAVAILABLE"
  | "PROVIDER_PROCESS_FAILED"
  | "PROCESS_TIMEOUT"
  | "SCHEMA_VALIDATION_FAILED"
  | "SECURITY_POLICY_VIOLATION"
  | "USER_CANCELLED"
  | "ARTIFACT_WRITE_FAILED"
  | "TOOL_DEFINITION_NOT_FOUND"
  | "TOOL_DUPLICATE_DEFINITION"
  | "TOOL_INVALID_DEFINITION"
  | "TOOL_INVALID_INPUT"
  | "TOOL_INVALID_OUTPUT"
  | "TOOL_INVALID_CONTEXT"
  | "TOOL_EXECUTION_FAILED"
  | "TOOL_CANCELLED"
  | "TOOL_TIMEOUT"
  | "TOOL_SERIALIZATION_FAILED"
  | "TOOL_ARTIFACT_WRITE_FAILED"
  | "INTERNAL_ERROR";

export interface SerializedError {
  name: string;
  message: string;
  code?: OpenFlowErrorCode | string;
  stack?: string;
  cause?: unknown;
}

export const EXIT_CODES = {
  SUCCESS: 0,
  WORKFLOW_FAILED: 1,
  CLI_USAGE_ERROR: 2,
  WORKFLOW_PARSE_OR_VALIDATION_ERROR: 3,
  PROVIDER_UNAVAILABLE: 4,
  SECURITY_POLICY_VIOLATION: 5,
  USER_CANCELLED: 6,
  TIMEOUT: 7,
  INTERNAL_ERROR: 8
} as const;

export type ExitCode = (typeof EXIT_CODES)[keyof typeof EXIT_CODES];

export function exitCodeForErrorCode(code: OpenFlowErrorCode): ExitCode {
  switch (code) {
    case "CLI_USAGE_ERROR":
    case "CONFIG_VALIDATION_ERROR":
      return EXIT_CODES.CLI_USAGE_ERROR;
    case "WORKFLOW_PARSE_ERROR":
    case "WORKFLOW_VALIDATION_ERROR":
      return EXIT_CODES.WORKFLOW_PARSE_OR_VALIDATION_ERROR;
    case "PROVIDER_UNAVAILABLE":
      return EXIT_CODES.PROVIDER_UNAVAILABLE;
    case "SECURITY_POLICY_VIOLATION":
      return EXIT_CODES.SECURITY_POLICY_VIOLATION;
    case "USER_CANCELLED":
      return EXIT_CODES.USER_CANCELLED;
    case "PROCESS_TIMEOUT":
      return EXIT_CODES.TIMEOUT;
    case "PROVIDER_PROCESS_FAILED":
    case "SCHEMA_VALIDATION_FAILED":
    case "TOOL_EXECUTION_FAILED":
    case "TOOL_INVALID_INPUT":
    case "TOOL_INVALID_OUTPUT":
    case "TOOL_SERIALIZATION_FAILED":
      return EXIT_CODES.WORKFLOW_FAILED;
    case "TOOL_TIMEOUT":
      return EXIT_CODES.TIMEOUT;
    case "TOOL_CANCELLED":
      return EXIT_CODES.USER_CANCELLED;
    case "TOOL_DEFINITION_NOT_FOUND":
    case "TOOL_DUPLICATE_DEFINITION":
    case "TOOL_INVALID_DEFINITION":
    case "TOOL_INVALID_CONTEXT":
      return EXIT_CODES.WORKFLOW_PARSE_OR_VALIDATION_ERROR;
    case "TOOL_ARTIFACT_WRITE_FAILED":
    case "ARTIFACT_WRITE_FAILED":
    case "INTERNAL_ERROR":
      return EXIT_CODES.INTERNAL_ERROR;
  }
}
